---
engines:
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
---
engines:
  fixme:
    enabled: true
  foodcritic:
    enabled: true
    config:
---
engines:
  fixme:
    enabled: true
  foodcritic:
    enabled: true
ratings:
---
engines:
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
---
engines:
  fixme:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
---
engines:
  fixme:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
---
engines:
  fixme:
    enabled: true
ratings:
  paths: []
exclude_paths: []
