---
engines:
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
---
engines:
  fixme:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
---
engines:
  fixme:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
---
engines:
  fixme:
    enabled: true
ratings:
  paths: []
exclude_paths: []
