---
engines:
  fixme:
    enabled: true
  eslint:
    enabled: true
    config: 
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  nodesecurity:
    enabled: false
